artifact_location: file:///C:/Users/USER/Desktop/vicko-20230316T180337Z-001/vicko/My
  Data Science/Machine Learning/ML Cap Stone Project/remote/0
creation_time: 1704136888350
experiment_id: '0'
last_update_time: 1704136888350
lifecycle_stage: active
name: Default
